### ISSUE TITLE
__proto__ & prototype

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/FEIQA#28]
# `__proto__` & `prototype`

***

https://stackoverflow.com/questions/3082791/javascript-and-proto-what-browsers-use-it

**Comment by xgqfrms** [comment]
# remove-all-listeners

https://stackoverflow.com/questions/9251837/how-to-remove-all-listeners-in-an-element

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/44759387-6985e380-ab6c-11e8-83d0-1ce0a7508877.png)

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/44759590-a0102e00-ab6d-11e8-9094-f6e35ed158b2.png)

**Comment by xgqfrms** [comment]
# listen EADDRINUSE :::6666

https://stackoverflow.com/questions/9898372/how-to-fix-error-listen-eaddrinuse-while-using-nodejs

**Comment by xgqfrms** [comment]
# windows 10 & port checker

```cmd

# admin
$ netstat -a -b 

```

https://stackoverflow.com/questions/31837690/what-program-in-windows-10-uses-port-80/31868649#31868649


![image](https://user-images.githubusercontent.com/7291672/44763045-f97f5980-ab7b-11e8-96d4-5529c0b5dd4b.png)

**Comment by xgqfrms** [comment]
# regx

![image](https://user-images.githubusercontent.com/7291672/44764720-ad381780-ab83-11e8-92a1-32a212bd9adc.png)

**Comment by xgqfrms** [comment]
# css & animation

> bug

```css
.showPanel {
    display: block;
    /* height: 100%; */
    -webkit-transition: display 1.0s 1.0s ease-in;
    transition: all 1.0s 1.0s ease-in;
}

.hidePanel {
    display: none;
    /* height: 0; */
    -webkit-transition: display 1.0s 1.0s ease-out;
    transition: all 1.0s 1.0s ease-out;
}

// 这段 CSS 为什么没有过度效果呢？ 

```
![image](https://user-images.githubusercontent.com/7291672/44764757-e7091e00-ab83-11e8-9835-f1a39b2ee14a.png)

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties
