### ISSUE TITLE
Chrome & extensions

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/FEIQA#70]
# Chrome & extensions

https://chrome.google.com/webstore/category/extensions

**Comment by xgqfrms** [comment]
# how to write a chrome extension

https://www.cnblogs.com/xgqfrms/p/10017780.html
https://github.com/xyzdata/RAIO/issues/215#issue-272066876

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/49908909-92ca4580-feb7-11e8-9efd-7d9f26c8ba1e.png)

**Comment by xgqfrms** [comment]
# chrome extensions & android

https://chrome.google.com/webstore

https://www.digitbin.com/install-chrome-extensions-android/

**Comment by xgqfrms** [comment]
#

**Comment by xgqfrms** [comment]
# chrome.tabs.executeScript

> popup.js

```js

// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


function click(e) {
    chrome.tabs.executeScript(null,{
        code: "document.body.style.backgroundColor='" + e.target.id + "'",
    });
    window.close();
}

document.addEventListener('DOMContentLoaded', function () {
    var divs = document.querySelectorAll('div');
    for (var i = 0; i < divs.length; i++) {
        divs[i].addEventListener('click', click);
    }
});

```

> manifest.json

```json

{
    "name": "A browser action with a popup that changes the page color",
    "description": "Change the current page color",
    "version": "1.0",
    "permissions": [
        "tabs",
        "http://*/*",
        "https://*/*"
    ],
    "browser_action": {
        "default_title": "Set this page's color.",
        "default_icon": "icon.png",
        "default_popup": "popup.html"
    },
    "manifest_version": 2
}

```

> popup.html

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Set Page Color Popup</title>
    <link rel="stylesheet" href="popup.css">
</head>

<body>
    <div id="red">red</div>
    <div id="blue">blue</div>
    <div id="green">green</div>
    <div id="yellow">yellow</div>
    <script src="popup.js"></script>
</body>

</html>

```

> popup.css

```css
body {
    overflow: hidden;
    margin: 0px;
    padding: 0px;
    background: white;
}

div:first-child {
    margin-top: 0px;
}

div {
    cursor: pointer;
    text-align: center;
    padding: 1px 3px;
    font-family: sans-serif;
    font-size: 0.8em;
    width: 100px;
    margin-top: 1px;
    background: #cccccc;
}

div:hover {
    background: #aaaaaa;
}

#red {
    border: 1px solid red;
    color: red;
}

#blue {
    border: 1px solid blue;
    color: blue;
}

#green {
    border: 1px solid green;
    color: green;
}

#yellow {
    border: 1px solid yellow;
    color: yellow;
}

```
