### ISSUE TITLE
css gradient text

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/FEIQA#91]
# css gradient text

https://cssgradient.io/blog/css-gradient-text/

```css

h1 {
  font-size: 72px;
  background: -webkit-linear-gradient(#eee, #333);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}


```

https://davidwalsh.name/css-gradient-text

```css

.gradient-text {
  /* standard gradient background */
  background: linear-gradient(red, blue);

  /* clip hackery */
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

```
https://css-tricks.com/snippets/css/gradient-text/

https://dev.to/paramharrison/gradient-text-style-using-css-11ka

https://codepen.io/leocampos/pen/pPwwNR

https://codepen.io/webgeeker/pen/mddMOJx

https://stackoverflow.com/questions/37831837/gradient-text-color
