### ISSUE TITLE
CSS filter

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/FEIQA#93]
# CSS filter

> grayscale 灰阶
 
https://developer.mozilla.org/en-US/docs/Web/CSS/filter

```css
body{
  -webkit-filter: grayscale(1);
  filter: grayscale(1);
}

```
/* OR */

```css
body{
  -webkit-filter: grayscale(100%);
  filter: grayscale(100%);
}

```

**Comment by xgqfrms** [comment]
```sh
https://github.com/haizlin/fe-interview/issues/1497#issuecomment-554172850

```

**Comment by xgqfrms** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/grayscale

https://css-tricks.com/almanac/properties/f/filter/

**Comment by xgqfrms** [comment]
```css
body{
  filter: grayscale(1) blur(1px);
}
```

![image](https://user-images.githubusercontent.com/7291672/68911169-0c854600-078f-11ea-9d77-2e4d3a19355c.png)
